/**
 * ClickUp task-id extraction and transition rules.
 *
 * Pure logic only — no network, no token. The token never passes through this
 * process: it lives as a repository secret and is read by the workflow that
 * runs on GitHub. Keeping this module I/O-free is what makes the branch→task
 * mapping and the "only move it if it is still to-do" decision testable.
 */

/** ClickUp's own default to-do status, plus the spellings teams commonly use. */
export const DEFAULT_TODO_STATUSES = ["to do", "todo", "open", "backlog", "pending"];

/**
 * Pulls the task id out of a branch name.
 *
 * Branches are `<prefix>/<taskIdPrefix><id>[/description]`, which the
 * nomenclature ruleset enforces at creation time — so a branch reaching a
 * merge without an id means the ruleset was bypassed, not that the format is
 * optional. Returns null rather than guessing.
 */
export function extractTaskId(branchName, { prefixes = [], taskIdPrefix = "CU-" } = {}) {
  if (!branchName) return null;

  const branch = String(branchName).replace(/^refs\/heads\//, "");
  const segments = branch.split("/");
  if (segments.length < 2) return null;

  const [prefix, candidate] = segments;
  if (prefixes.length > 0 && !prefixes.includes(prefix)) return null;
  if (!candidate.startsWith(taskIdPrefix)) return null;

  const id = candidate.slice(taskIdPrefix.length);
  return id.length > 0 ? id : null;
}

/**
 * Decides whether a task should move, given the status it is currently in.
 *
 * Only a to-do task advances. A task already in progress, in review, or done
 * is left alone — a later merge must never drag a task backwards, which is the
 * failure mode that makes people distrust this kind of automation.
 */
export function decideTransition(currentStatus, { todoStatuses = DEFAULT_TODO_STATUSES, target = "in progress" } = {}) {
  const current = String(currentStatus ?? "").trim().toLowerCase();

  if (!current) return { move: false, reason: "the task has no readable status" };
  if (current === target.toLowerCase()) return { move: false, reason: `already '${currentStatus}'` };

  if (!todoStatuses.map((s) => s.toLowerCase()).includes(current)) {
    return { move: false, reason: `status '${currentStatus}' is past to-do; leaving it alone` };
  }

  return { move: true, target, reason: `'${currentStatus}' is a to-do status` };
}

/** Single-quoted shell literal; the only user-controlled values are from config. */
const shellQuote = (value) => `'${String(value).replace(/'/g, `'\\''`)}'`;

export const WORKFLOW_PATH = ".github/workflows/clickup-sync.yml";

/**
 * Renders the workflow that performs the transition on GitHub.
 *
 * The work runs there rather than locally because a merge is a GitHub event:
 * nothing on a developer's machine can react to someone else merging a PR.
 *
 * The token is read from a repository secret and never interpolated into the
 * YAML — the file is committed in plain sight, so it must stay free of it.
 */
export function renderWorkflow(clickup = {}) {
  const branch = clickup.targetBranch ?? "dev";
  const idPrefix = clickup.taskIdPrefix ?? "CU-";
  const target = clickup.targetStatus ?? "in progress";
  const todo = clickup.todoStatuses ?? DEFAULT_TODO_STATUSES;

  const cases = todo.map((s) => shellQuote(String(s).toLowerCase())).join("|");

  return `# Generated by engineering-ruleset-plugin. Re-run the sync to update it;
# local edits are overwritten.
name: ClickUp task sync

on:
  pull_request:
    types: [closed]
    branches: [${branch}]

permissions:
  contents: read

jobs:
  advance-task:
    # Closing a PR without merging must not touch the task.
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Advance the linked ClickUp task
        env:
          CLICKUP_TOKEN: \${{ secrets.CLICKUP_TOKEN }}
          # Only needed when the workspace uses ClickUp Custom Task IDs.
          CLICKUP_TEAM_ID: \${{ secrets.CLICKUP_TEAM_ID }}
          HEAD_REF: \${{ github.event.pull_request.head.ref }}
        run: |
          set -euo pipefail

          if [ -z "\${CLICKUP_TOKEN:-}" ]; then
            echo "::warning::CLICKUP_TOKEN is not set; skipping ClickUp sync."
            exit 0
          fi

          # Branches are <prefix>/${idPrefix}<id>[/description], enforced by the
          # branch-nomenclature ruleset.
          id="$(printf '%s' "$HEAD_REF" | awk -F/ -v p=${shellQuote(idPrefix)} \\
            'index($2, p) == 1 { print substr($2, length(p) + 1) }')"

          if [ -z "$id" ]; then
            echo "::warning::No ${idPrefix} task id in '$HEAD_REF'; nothing to sync."
            exit 0
          fi

          query=""
          if [ -n "\${CLICKUP_TEAM_ID:-}" ]; then
            query="?custom_task_ids=true&team_id=\${CLICKUP_TEAM_ID}"
          fi
          url="https://api.clickup.com/api/v2/task/\${id}\${query}"

          status="$(curl -sS -f -H "Authorization: $CLICKUP_TOKEN" "$url" \\
            | jq -r '.status.status // empty')"
          echo "Task $id is currently '\${status:-unknown}'."

          lower="$(printf '%s' "$status" | tr '[:upper:]' '[:lower:]')"
          case "$lower" in
            ${cases})
              ;;
            *)
              echo "Not a to-do status; leaving task $id untouched."
              exit 0
              ;;
          esac

          curl -sS -f -X PUT \\
            -H "Authorization: $CLICKUP_TOKEN" \\
            -H "Content-Type: application/json" \\
            -d ${shellQuote(JSON.stringify({ status: target }))} \\
            "$url" > /dev/null

          echo "Task $id moved to '${target}'."
`;
}

/**
 * Works out what the ClickUp side of a sync would change. Read-only.
 *
 * The secret is only ever *checked for*, never written: a token pasted through
 * this tool would land in shell history and in the process table, so setting
 * it stays the user's own step via `gh secret set`, which reads it silently.
 */
export async function planClickUp(client, clickup) {
  if (!clickup?.enabled) return null;

  const desired = renderWorkflow(clickup);
  const existing = await client.getFile(WORKFLOW_PATH);

  return {
    path: WORKFLOW_PATH,
    action: !existing ? "create" : existing.content === desired ? "unchanged" : "update",
    content: desired,
    sha: existing?.sha,
    hasToken: await client.hasSecret(clickup.secretName ?? "CLICKUP_TOKEN"),
    secretName: clickup.secretName ?? "CLICKUP_TOKEN",
  };
}

/** Writes the workflow. The secret is never touched. */
export async function applyClickUp(client, step) {
  if (!step || step.action === "unchanged") return { status: "unchanged" };

  await client.putFile(
    step.path,
    step.content,
    `ci: ${step.action} ClickUp task sync workflow`,
    step.sha,
  );
  return { status: "applied", action: step.action };
}
