/**
 * Pull-request check workflows: the AI scope check, and the PR-Agent reviewer.
 *
 * These are generated into the target repository the same way the task-sync
 * workflow is — same ownership marker, same relax window, same never-touch-a
 * -file-we-did-not-write rule. The difference is that a scope check needs a
 * TRACKER to read the ticket from, so its issue-provider block is derived from
 * `taskSync.provider` rather than configured twice: pick ClickUp and it reads
 * ClickUp, pick Jira and it reads Jira, with the matching credentials wired in.
 *
 * The scope-check logic itself lives in assets/scope-check.mjs and is copied
 * verbatim. It is entirely environment-driven, so there is nothing to template
 * inside it — which also keeps a 400-line script out of a JS template literal.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

export const SCOPE_CHECK_WORKFLOW_PATH = ".github/workflows/pr-scope-check.yml";
export const SCOPE_CHECK_SCRIPT_PATH = ".github/scripts/scope-check.mjs";
export const PR_AGENT_WORKFLOW_PATH = ".github/workflows/pr-agent.yml";

/** Matches tasksync.js, so one ownership test covers every generated file. */
export const GENERATED_MARKER = "# Generated by engineering-ruleset-plugin";
/** The same claim, in a comment syntax a .mjs file accepts. */
export const GENERATED_MARKER_JS = "// Generated by engineering-ruleset-plugin";

/** Single-quoted YAML scalar; `no`/`on`/`2` must not become a bool or number. */
const yamlQuote = (value) => `'${String(value).replace(/'/g, "''")}'`;

/** JSON-ish scalar for an env value that GitHub Actions reads as a string. */
const envString = (value) => `"${String(value).replace(/"/g, '\\"')}"`;

/**
 * How each tracker is wired into the scope-check step: which secrets and
 * variables it needs, and what `ISSUE_PROVIDER` to select. Keyed by the same
 * provider names `taskSync.provider` uses, so the two can never disagree.
 */
const ISSUE_PROVIDER_ENV = {
  clickup: {
    label: "ClickUp",
    lines: ["CLICKUP_TOKEN: ${{ secrets.CLICKUP_TOKEN }}"],
    secrets: ["CLICKUP_TOKEN"],
    variables: [],
  },
  jira: {
    label: "Jira",
    lines: [
      "JIRA_BASE_URL: ${{ vars.JIRA_BASE_URL }}",
      "JIRA_EMAIL: ${{ vars.JIRA_EMAIL }}",
      "JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}",
    ],
    secrets: ["JIRA_API_TOKEN"],
    variables: ["JIRA_BASE_URL", "JIRA_EMAIL"],
  },
};

/**
 * Resolves the `prChecks` section, filling in defaults. Returns `enabled:
 * false` shapes rather than null so a caller can still tell "off" from
 * "never configured" when deciding whether to clean up an existing file.
 */
export function normalizePrChecks(config) {
  const raw = config?.prChecks ?? {};
  const scope = raw.scopeCheck ?? {};
  const agent = raw.prAgent ?? {};

  return {
    scopeCheck: {
      enabled: scope.enabled ?? false,
      aiProvider: scope.aiProvider ?? "openrouter",
      aiModel: scope.aiModel ?? "qwen/qwen3-coder",
      aiKeySecret: scope.aiKeySecret ?? "OPENROUTER_API_KEY",
      requireTask: scope.requireTask ?? true,
      failOpenOnError: scope.failOpenOnError ?? false,
      maxDiffChars: scope.maxDiffChars ?? 60000,
      autoCloseOutOfScope: scope.autoCloseOutOfScope ?? true,
    },
    prAgent: {
      enabled: agent.enabled ?? false,
      model: agent.model ?? "openrouter/qwen/qwen3-coder",
      fallbackModels: agent.fallbackModels ?? ["openrouter/qwen/qwen-2.5-72b-instruct"],
      maxTokens: agent.maxTokens ?? 32000,
      numCodeSuggestions: agent.numCodeSuggestions ?? 4,
      keySecret: agent.keySecret ?? "OPENROUTER_API_KEY",
      securityGate: agent.securityGate ?? true,
    },
  };
}

/**
 * The scope-check workflow.
 *
 * Triggered on pull requests targeting any declared environment — the same
 * list that drives every other ruleset, so adding an environment extends this
 * check to it without a second edit. The job id is `scope-check`, which is
 * exactly the context name `PR-SCOPE-CHECK` requires: rename one and the
 * required check waits forever for a check nobody reports.
 */
export function renderScopeCheckWorkflow({ environments, provider, scopeCheck }) {
  if (environments.length === 0) {
    throw new Error("Cannot render a scope-check workflow with no environment branches to target.");
  }
  const issue = ISSUE_PROVIDER_ENV[provider];
  if (!issue) {
    throw new Error(`Cannot render a scope-check workflow for issue provider '${provider}'.`);
  }

  const trackerEnv = issue.lines.map((line) => `          ${line}`).join("\n");

  return `${GENERATED_MARKER}. Re-run the sync to update it;
# local edits are overwritten.
#
# Reads the ticket from ${issue.label} (taskSync.provider), asks an AI whether the
# PR's changes stay within that ticket's scope, and blocks the merge if not.
name: PR Scope Check

on:
  pull_request:
    # The branches a PR can TARGET for this check to run — every environment
    # declared in ruleset-config.json.
    branches:
${environments.map((env) => `      - ${yamlQuote(env)}`).join("\n")}
    types: [opened, synchronize, reopened, edited]

# Cancel an in-flight run when the PR is updated again
concurrency:
  group: scope-check-\${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write # to post the sticky comment

jobs:
  # This job id IS the required status check context named by the
  # PR-SCOPE-CHECK ruleset. Renaming it silently blocks every merge.
  scope-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run scope check
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          REPO: \${{ github.repository }}
          PR_NUMBER: \${{ github.event.pull_request.number }}

          # ---- AI provider ----
          AI_PROVIDER: ${envString(scopeCheck.aiProvider)}
          # Keep this on a model the key can actually run: a free-tier id that
          # answers with an empty completion reaches FAIL_OPEN_ON_ERROR=false
          # and blocks every PR.
          AI_MODEL: ${envString(scopeCheck.aiModel)}
          OPENROUTER_API_KEY: \${{ secrets.${scopeCheck.aiKeySecret} }}

          # ---- issue tracker (from taskSync.provider) ----
          ISSUE_PROVIDER: ${envString(provider)}
${trackerEnv}

          # ---- behaviour ----
          REQUIRE_TASK: ${envString(String(scopeCheck.requireTask))}
          FAIL_OPEN_ON_ERROR: ${envString(String(scopeCheck.failOpenOnError))}
          MAX_DIFF_CHARS: ${envString(String(scopeCheck.maxDiffChars))}
          AUTO_CLOSE_OUT_OF_SCOPE: ${envString(String(scopeCheck.autoCloseOutOfScope))}
        run: node ${SCOPE_CHECK_SCRIPT_PATH}
`;
}

/** The scope-check script, verbatim from the plugin's own asset. */
export function renderScopeCheckScript() {
  const source = readFileSync(fileURLToPath(new URL("../assets/scope-check.mjs", import.meta.url)), "utf8");
  return `${GENERATED_MARKER_JS}. Re-run the sync to update it;\n// local edits are overwritten.\n${source}`;
}

/**
 * The PR-Agent reviewer workflow.
 *
 * `security_gate` is a second job rather than part of the review: PR-Agent
 * labels the pull request when it finds a security concern, and a label is
 * only readable after the reviewer has finished, so the gate has to run
 * after it and fail on what it finds.
 */
export function renderPrAgentWorkflow({ prAgent }) {
  const gate = prAgent.securityGate
    ? `
  # Blocking gate: if PR-Agent's review labelled the PR with a security concern,
  # fail the check and tell the author to fix it first (pointing at PR-Agent's
  # own review comment, which already describes the concern and the fix).
  security_gate:
    name: security gate
    needs: pr_agent
    if: \${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check PR-Agent security label
        env:
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          REPO: \${{ github.repository }}
          PR_NUMBER: \${{ github.event.pull_request.number }}
        run: |
          set -euo pipefail
          # PR-Agent adds this label (wording may vary by version) on a security concern.
          LABELS=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json labels --jq '.labels[].name' || true)
          echo "PR labels: \${LABELS:-<none>}"
          if printf '%s\\n' "$LABELS" | grep -qiE 'security concern|possible security'; then
            BODY=$(printf '%s\\n' \\
              '<!-- pr-agent-security-gate -->' \\
              '### 🚫 Security gate failed — merge blocked' \\
              '' \\
              '**PR-Agent flagged a security concern in this pull request.**' \\
              'Security is being violated — fix this first before the PR can be merged.' \\
              '' \\
              'See the **Security concerns** section of PR-Agent’s review comment above for the' \\
              'specific issue and the recommended fix. Resolve it and push again — this check re-runs automatically.')
            gh pr comment "$PR_NUMBER" --repo "$REPO" --body "$BODY" || true
            echo "::error::Security gate failed — PR-Agent flagged a security concern."
            exit 1
          fi
          echo "::notice::No PR-Agent security concern label found — security gate passed."
`
    : "";

  return `${GENERATED_MARKER}. Re-run the sync to update it;
# local edits are overwritten.
name: PR Agent Review

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment: # lets the team trigger /review, /describe, /improve manually

permissions:
  issues: write
  pull-requests: write
  contents: write
  checks: write

jobs:
  pr_agent:
    # skip bot-authored events (e.g. our own sticky comments) to avoid loops
    if: \${{ github.event.sender.type != 'Bot' }}
    name: review
    runs-on: ubuntu-latest
    steps:
      - name: PR Agent
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}

          # ---- model ----
          CONFIG__MODEL: ${envString(prAgent.model)}
          CONFIG__FALLBACK_MODELS: ${envString(JSON.stringify(prAgent.fallbackModels))}
          CONFIG__CUSTOM_MODEL_MAX_TOKENS: ${envString(String(prAgent.maxTokens))}
          OPENROUTER__KEY: \${{ secrets.${prAgent.keySecret} }}

          # ---- what runs automatically on PR open ----
          github_action_config.auto_describe: "true" # short summary at the top of the PR
          github_action_config.auto_review: "true" # detailed review comment
          github_action_config.auto_improve: "true" # inline code suggestions

          # ---- output shaping ----
          PR_DESCRIPTION__EXTRA_INSTRUCTIONS: "Keep the summary to a maximum of 2 lines. Be concrete about what changed."
          # Keep the author's original description (it may contain the ticket link
          # that the scope-check workflow reads) — never replace it.
          PR_DESCRIPTION__ADD_ORIGINAL_USER_DESCRIPTION: "true"
          PR_DESCRIPTION__GENERATE_AI_TITLE: "false" # titles may carry the ticket id — don't touch
          PR_REVIEWER__EXTRA_INSTRUCTIONS: "Give detailed, actionable recommendations with concrete file/line references. Prioritise correctness, security and maintainability."
          PR_CODE_SUGGESTIONS__NUM_CODE_SUGGESTIONS: ${envString(String(prAgent.numCodeSuggestions))}

          # ---- security gating ----
          # Make the reviewer add a PR label when it finds a security concern, and
          # always run the security review. The security_gate job below reads that
          # label and fails the check when a concern is present.
          PR_REVIEWER__ENABLE_REVIEW_LABELS_SECURITY: "true"
          PR_REVIEWER__REQUIRE_SECURITY_REVIEW: "true"
${gate}`;
}

/**
 * Works out which PR-check files need writing. Read-only.
 *
 * @returns {Promise<{files: Array<{path, action, content, sha, label}>,
 *                    blocked: Array<{what: string, reason: string}>,
 *                    secrets: string[], variables: string[]}>}
 *   `blocked` explains anything the config asked for that cannot be generated
 *   here, rather than leaving it silently absent.
 */
export async function planPrChecks(client, config, { provider }) {
  const checks = normalizePrChecks(config);
  const environments = Object.keys(config?.environments ?? {});
  const files = [];
  const blocked = [];
  const secrets = new Set();
  const variables = new Set();

  const add = async (path, content, label) => {
    const existing = await client.getFile(path);
    const marker = path.endsWith(".mjs") ? GENERATED_MARKER_JS : GENERATED_MARKER;
    files.push({
      path,
      label,
      content,
      sha: existing?.sha,
      action: !existing ? "create" : existing.content === content ? "unchanged" : "update",
      // An existing file without the marker was written by hand — adopting it
      // means this plugin overwrites work someone else did, and regenerates
      // over it on every run afterwards. That is a reasonable thing to want,
      // but never a reasonable thing to do silently.
      adopting: Boolean(existing) && !existing.content.startsWith(marker),
    });
  };

  if (checks.scopeCheck.enabled) {
    // A scope check with no tracker has nothing to read the ticket from, and
    // no environment branches has nothing to trigger on. Either way, saying so
    // beats writing a workflow that could only ever fail.
    if (!ISSUE_PROVIDER_ENV[provider]) {
      blocked.push({
        what: SCOPE_CHECK_WORKFLOW_PATH,
        reason:
          "it reads the ticket from a task tracker, but taskSync is off (provider 'none') — " +
          "enable ClickUp or Jira, or set prChecks.scopeCheck.enabled to false",
      });
    } else if (environments.length === 0) {
      blocked.push({
        what: SCOPE_CHECK_WORKFLOW_PATH,
        reason: "no environment branches are declared, so there is nothing for it to trigger on",
      });
    } else {
      await add(
        SCOPE_CHECK_WORKFLOW_PATH,
        renderScopeCheckWorkflow({ environments, provider, scopeCheck: checks.scopeCheck }),
        "PR scope check",
      );
      await add(SCOPE_CHECK_SCRIPT_PATH, renderScopeCheckScript(), "PR scope check script");
      secrets.add(checks.scopeCheck.aiKeySecret);
      for (const name of ISSUE_PROVIDER_ENV[provider].secrets) secrets.add(name);
      for (const name of ISSUE_PROVIDER_ENV[provider].variables) variables.add(name);
    }
  }

  if (checks.prAgent.enabled) {
    await add(PR_AGENT_WORKFLOW_PATH, renderPrAgentWorkflow({ prAgent: checks.prAgent }), "PR Agent review");
    secrets.add(checks.prAgent.keySecret);
  }

  return { files, blocked, secrets: [...secrets], variables: [...variables] };
}

/**
 * Generated PR-check files that are no longer wanted — the feature was turned
 * off, or its tracker went away. Ownership is proven by the generated marker,
 * exactly as for the sync workflows: a file a team wrote by hand at one of
 * these paths is theirs, and is never deleted.
 */
export async function planPrCheckOrphans(client, plannedPaths) {
  const orphans = [];
  for (const path of [SCOPE_CHECK_WORKFLOW_PATH, SCOPE_CHECK_SCRIPT_PATH, PR_AGENT_WORKFLOW_PATH]) {
    if (plannedPaths.includes(path)) continue;
    const existing = await client.getFile(path);
    if (!existing) continue;
    const marker = path.endsWith(".mjs") ? GENERATED_MARKER_JS : GENERATED_MARKER;
    if (existing.content.startsWith(marker)) orphans.push({ path, sha: existing.sha });
  }
  return orphans;
}

/** Writes one PR-check file. */
export async function applyPrCheckFile(client, file) {
  if (file.action === "unchanged") return { status: "unchanged" };
  await client.putFile(file.path, file.content, `ci: ${file.action} ${file.label}`, file.sha);
  return { status: "applied", action: file.action };
}

/** Removes one orphaned PR-check file. */
export async function removePrCheckOrphan(client, orphan) {
  await client.deleteFile(orphan.path, `ci: remove ${orphan.path} (no longer enabled)`, orphan.sha);
}
