/**
 * Task-tracker sync: on a merge into the target branch, advance the linked
 * task. Two providers — ClickUp and Jira — behind one plan/apply surface.
 *
 * Pure logic plus workflow rendering — no network beyond what the client
 * does, and never a token: credentials live as repository secrets and are
 * read only by the workflow running on GitHub. The conventions match the
 * pr-guardrails scope-check suite (`ISSUE_PROVIDER: clickup | jira`,
 * `JIRA_BASE_URL`/`JIRA_EMAIL` variables + `JIRA_API_TOKEN` secret), so one
 * repository setup feeds both tools.
 */

/** ClickUp's own default to-do status, plus the spellings teams commonly use. */
export const DEFAULT_TODO_STATUSES = ["to do", "todo", "open", "backlog", "pending"];

export const PROVIDERS = {
  clickup: {
    label: "ClickUp",
    workflowPath: ".github/workflows/clickup-sync.yml",
    secretName: "CLICKUP_TOKEN",
    taskIdPrefix: "CU-",
    requiredVariables: [],
    tokenHint: "ClickUp → Settings → Apps → API Token",
  },
  jira: {
    label: "Jira",
    workflowPath: ".github/workflows/jira-sync.yml",
    secretName: "JIRA_API_TOKEN",
    taskIdPrefix: "",
    requiredVariables: ["JIRA_BASE_URL", "JIRA_EMAIL"],
    tokenHint: "id.atlassian.com → Security → Create and manage API tokens",
  },
};

/**
 * Resolves the task-sync section of the policy to one normalized shape.
 *
 * `taskSync` is the section's name; a legacy `clickup` section is honoured
 * as `provider: "clickup"` so configs written before providers existed keep
 * working unchanged. Returns null when the feature is off.
 */
export function normalizeTaskSync(config) {
  const raw = config?.taskSync ?? config?.clickup;
  if (!raw?.enabled) return null;

  const provider = raw.provider ?? "clickup";
  const known = PROVIDERS[provider];
  if (!known) {
    throw new Error(
      `Unknown task-sync provider '${provider}'. Supported: ${Object.keys(PROVIDERS).join(", ")}.`,
    );
  }

  return {
    provider,
    targetBranch: raw.targetBranch ?? "dev",
    taskIdPrefix: raw.taskIdPrefix ?? known.taskIdPrefix,
    todoStatuses: raw.todoStatuses ?? DEFAULT_TODO_STATUSES,
    targetStatus: raw.targetStatus ?? "in progress",
    secretName: raw.secretName ?? known.secretName,
  };
}

/**
 * Pulls the task id out of a branch name.
 *
 * Branches are `<prefix>/<taskIdPrefix><id>[/description]`, which the
 * nomenclature ruleset enforces at creation time — so a branch reaching a
 * merge without an id means the ruleset was bypassed, not that the format is
 * optional. Returns null rather than guessing.
 */
export function extractTaskId(branchName, { prefixes = [], taskIdPrefix = "CU-" } = {}) {
  if (!branchName) return null;

  const branch = String(branchName).replace(/^refs\/heads\//, "");
  const segments = branch.split("/");
  if (segments.length < 2) return null;

  const [prefix, candidate] = segments;
  if (prefixes.length > 0 && !prefixes.includes(prefix)) return null;
  if (!candidate.startsWith(taskIdPrefix)) return null;

  const id = candidate.slice(taskIdPrefix.length);
  return id.length > 0 ? id : null;
}

/**
 * Decides whether a task should move, given the status it is currently in.
 *
 * Only a to-do task advances. A task already in progress, in review, or done
 * is left alone — a later merge must never drag a task backwards, which is the
 * failure mode that makes people distrust this kind of automation.
 */
export function decideTransition(currentStatus, { todoStatuses = DEFAULT_TODO_STATUSES, target = "in progress" } = {}) {
  const current = String(currentStatus ?? "").trim().toLowerCase();

  if (!current) return { move: false, reason: "the task has no readable status" };
  if (current === target.toLowerCase()) return { move: false, reason: `already '${currentStatus}'` };

  if (!todoStatuses.map((s) => s.toLowerCase()).includes(current)) {
    return { move: false, reason: `status '${currentStatus}' is past to-do; leaving it alone` };
  }

  return { move: true, target, reason: `'${currentStatus}' is a to-do status` };
}

/** The first line of every rendered workflow — the ownership marker. */
export const GENERATED_MARKER = "# Generated by engineering-ruleset-plugin";

/** Single-quoted shell literal; the only user-controlled values are from config. */
const shellQuote = (value) => `'${String(value).replace(/'/g, `'\\''`)}'`;

/**
 * Renders the ClickUp workflow. Byte-stable for existing configs: a repo
 * synced before providers existed must plan `unchanged`, not `update`.
 */
export function renderClickUpWorkflow(sync = {}) {
  const branch = sync.targetBranch ?? "dev";
  const idPrefix = sync.taskIdPrefix ?? "CU-";
  const target = sync.targetStatus ?? "in progress";
  const todo = sync.todoStatuses ?? DEFAULT_TODO_STATUSES;
  // Must match what planTaskSync checks and --set-token sets, or the
  // committed workflow would read a secret nobody ever wrote.
  const secretName = sync.secretName ?? "CLICKUP_TOKEN";

  const cases = todo.map((s) => shellQuote(String(s).toLowerCase())).join("|");

  return `# Generated by engineering-ruleset-plugin. Re-run the sync to update it;
# local edits are overwritten.
name: ClickUp task sync

on:
  pull_request:
    types: [closed]
    branches: [${branch}]
  # Manual test entry: simulates a merged branch without needing a real PR,
  # so the wiring (secret, id extraction, ClickUp auth) can be verified alone.
  workflow_dispatch:
    inputs:
      head_ref:
        description: "Branch name to simulate, e.g. feature/${idPrefix}123/thing"
        required: true
        type: string

permissions:
  contents: read

jobs:
  advance-task:
    # Closing a PR without merging must not touch the task.
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Advance the linked ClickUp task
        env:
          CLICKUP_TOKEN: \${{ secrets.${secretName} }}
          # Only needed when the workspace uses ClickUp Custom Task IDs.
          CLICKUP_TEAM_ID: \${{ secrets.CLICKUP_TEAM_ID }}
          HEAD_REF: \${{ github.event.pull_request.head.ref || inputs.head_ref }}
        run: |
          set -euo pipefail

          if [ -z "\${CLICKUP_TOKEN:-}" ]; then
            echo "::warning::CLICKUP_TOKEN is not set; skipping ClickUp sync."
            exit 0
          fi

          # Branches are <prefix>/${idPrefix}<id>[/description], enforced by the
          # branch-nomenclature ruleset.
          id="$(printf '%s' "$HEAD_REF" | awk -F/ -v p=${shellQuote(idPrefix)} \\
            'index($2, p) == 1 { print substr($2, length(p) + 1) }')"

          if [ -z "$id" ]; then
            echo "::warning::No ${idPrefix} task id in '$HEAD_REF'; nothing to sync."
            exit 0
          fi

          query=""
          if [ -n "\${CLICKUP_TEAM_ID:-}" ]; then
            query="?custom_task_ids=true&team_id=\${CLICKUP_TEAM_ID}"
          fi
          url="https://api.clickup.com/api/v2/task/\${id}\${query}"

          status="$(curl -sS -f -H "Authorization: $CLICKUP_TOKEN" "$url" \\
            | jq -r '.status.status // empty')"
          echo "Task $id is currently '\${status:-unknown}'."

          lower="$(printf '%s' "$status" | tr '[:upper:]' '[:lower:]')"
          case "$lower" in
            ${cases})
              ;;
            *)
              echo "Not a to-do status; leaving task $id untouched."
              exit 0
              ;;
          esac

          curl -sS -f -X PUT \\
            -H "Authorization: $CLICKUP_TOKEN" \\
            -H "Content-Type: application/json" \\
            -d ${shellQuote(JSON.stringify({ status: target }))} \\
            "$url" > /dev/null

          echo "Task $id moved to '${target}'."
`;
}

/**
 * Renders the Jira workflow.
 *
 * Same shape and guarantees as the ClickUp one, with Jira's model mapped in:
 * the issue key is the standard `PROJ-123` form found in the branch's second
 * segment (after the optional taskIdPrefix), status comes from
 * `fields.status.name`, and the move is a transition looked up by name at run
 * time — Jira transition ids are per-project, so they cannot be baked in.
 * Auth follows the scope-check convention: JIRA_BASE_URL and JIRA_EMAIL as
 * repository variables (not sensitive), JIRA_API_TOKEN as a secret.
 */
export function renderJiraWorkflow(sync = {}) {
  const branch = sync.targetBranch ?? "dev";
  const idPrefix = sync.taskIdPrefix ?? "";
  const target = sync.targetStatus ?? "in progress";
  const todo = sync.todoStatuses ?? DEFAULT_TODO_STATUSES;
  const secretName = sync.secretName ?? "JIRA_API_TOKEN";

  const cases = todo.map((s) => shellQuote(String(s).toLowerCase())).join("|");
  const example = `${idPrefix}PROJ-123`;

  return `# Generated by engineering-ruleset-plugin. Re-run the sync to update it;
# local edits are overwritten.
name: Jira issue sync

on:
  pull_request:
    types: [closed]
    branches: [${branch}]
  # Manual test entry: simulates a merged branch without needing a real PR,
  # so the wiring (variables, secret, key extraction, Jira auth) can be
  # verified alone.
  workflow_dispatch:
    inputs:
      head_ref:
        description: "Branch name to simulate, e.g. feature/${example}/thing"
        required: true
        type: string

permissions:
  contents: read

jobs:
  advance-issue:
    # Closing a PR without merging must not touch the issue.
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Advance the linked Jira issue
        env:
          JIRA_BASE_URL: \${{ vars.JIRA_BASE_URL }}
          JIRA_EMAIL: \${{ vars.JIRA_EMAIL }}
          JIRA_API_TOKEN: \${{ secrets.${secretName} }}
          HEAD_REF: \${{ github.event.pull_request.head.ref || inputs.head_ref }}
        run: |
          set -euo pipefail

          if [ -z "\${JIRA_API_TOKEN:-}" ] || [ -z "\${JIRA_BASE_URL:-}" ] || [ -z "\${JIRA_EMAIL:-}" ]; then
            echo "::warning::JIRA_BASE_URL, JIRA_EMAIL, or JIRA_API_TOKEN is not set; skipping Jira sync."
            exit 0
          fi
          base="\${JIRA_BASE_URL%/}"
          want=${shellQuote(target)}

          # Branches are <prefix>/${idPrefix}<KEY>[/description]; the key is the
          # standard Jira form PROJ-123.
          seg="$(printf '%s' "$HEAD_REF" | awk -F/ -v p=${shellQuote(idPrefix)} \\
            'index($2, p) == 1 { print substr($2, length(p) + 1) }')"
          key="$(printf '%s' "$seg" | grep -oE '^[A-Za-z][A-Za-z0-9]*-[0-9]+' \\
            | head -1 | tr '[:lower:]' '[:upper:]' || true)"

          if [ -z "$key" ]; then
            echo "::warning::No Jira issue key in '$HEAD_REF'; nothing to sync."
            exit 0
          fi

          status="$(curl -sS -f -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \\
            "$base/rest/api/3/issue/$key?fields=status" \\
            | jq -r '.fields.status.name // empty')"
          echo "Issue $key is currently '\${status:-unknown}'."

          lower="$(printf '%s' "$status" | tr '[:upper:]' '[:lower:]')"
          case "$lower" in
            ${cases})
              ;;
            *)
              echo "Not a to-do status; leaving issue $key untouched."
              exit 0
              ;;
          esac

          # Transition ids are per-project; find the one whose name (or target
          # status) matches at run time.
          transition="$(curl -sS -f -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \\
            "$base/rest/api/3/issue/$key/transitions" \\
            | jq -r --arg t ${shellQuote(target.toLowerCase())} \\
              '.transitions[] | select(((.name // "") | ascii_downcase) == $t or ((.to.name // "") | ascii_downcase) == $t) | .id' \\
            | head -1 || true)"

          if [ -z "$transition" ]; then
            echo "::error::Issue $key has no transition to '$want' from '$status' — check the Jira workflow scheme."
            exit 1
          fi

          curl -sS -f -X POST \\
            -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \\
            -H "Content-Type: application/json" \\
            -d "{\\"transition\\":{\\"id\\":\\"$transition\\"}}" \\
            "$base/rest/api/3/issue/$key/transitions" > /dev/null

          echo "Issue $key moved to '$want'."
`;
}

export const renderWorkflow = (sync) =>
  (sync?.provider ?? "clickup") === "jira" ? renderJiraWorkflow(sync) : renderClickUpWorkflow(sync);

/**
 * Works out what the task-sync side of a sync would change. Read-only.
 *
 * Credentials are only ever *checked for*, never written or read back: the
 * secret check can only say whether one exists, and required Jira variables
 * are reported by name when missing.
 */
export async function planTaskSync(client, config) {
  const sync = normalizeTaskSync(config);
  if (!sync) return null;

  const known = PROVIDERS[sync.provider];
  const desired = renderWorkflow(sync);
  const existing = await client.getFile(known.workflowPath);

  const missingVariables = [];
  for (const name of known.requiredVariables) {
    if (!(await client.hasVariable(name))) missingVariables.push(name);
  }

  return {
    provider: sync.provider,
    providerLabel: known.label,
    path: known.workflowPath,
    action: !existing ? "create" : existing.content === desired ? "unchanged" : "update",
    content: desired,
    sha: existing?.sha,
    hasToken: await client.hasSecret(sync.secretName),
    secretName: sync.secretName,
    missingVariables,
    tokenHint: known.tokenHint,
    targetBranch: sync.targetBranch,
    targetStatus: sync.targetStatus,
  };
}

/**
 * Sync workflows at managed paths that belong to a provider OTHER than the
 * active one — left behind by a provider switch. They keep firing on every
 * merge (both trackers would move tasks), so the plan removes them. Only the
 * two managed paths are ever considered; nothing else in .github/workflows
 * is touched.
 */
export async function planSyncOrphans(client, activeProvider) {
  const orphans = [];
  for (const [name, def] of Object.entries(PROVIDERS)) {
    if (name === activeProvider) continue;
    const existing = await client.getFile(def.workflowPath);
    // Ownership is proven by the generated marker, not by the path: a file a
    // team wrote by hand at this path is theirs, and this plugin never
    // deletes what it did not create.
    if (existing && existing.content.startsWith(GENERATED_MARKER)) {
      orphans.push({ provider: name, providerLabel: def.label, path: def.workflowPath, sha: existing.sha });
    }
  }
  return orphans;
}

/** Removes one orphaned sync workflow. */
export async function removeSyncOrphan(client, orphan) {
  await client.deleteFile(
    orphan.path,
    `ci: remove ${orphan.providerLabel} task sync workflow (provider changed)`,
    orphan.sha,
  );
}

/** Writes the workflow. Credentials are never touched. */
export async function applyTaskSync(client, step) {
  if (!step || step.action === "unchanged") return { status: "unchanged" };

  await client.putFile(
    step.path,
    step.content,
    `ci: ${step.action} ${step.providerLabel} task sync workflow`,
    step.sha,
  );
  return { status: "applied", action: step.action };
}
